services:
  - type: web
    name: doclytics-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
